#!/bin/bash

## Debugging
# set -x

## Editable variables
DARK_COLOR_SCHEME=/usr/share/color-schemes/BreezeDark.colors
LIGHT_COLOR_SCHEME=/usr/share/color-schemes/BreezeLight.colors

KWINRULES=~/.config/kwinrulesrc

echo "Click on app you want to configure"
##     ----- | Find app WM class         | get after '='   | remove "    | remove ,      | change to lowercase     | only last value
name=$(xprop | grep "WM_CLASS(STRING) =" | cut -f3- -d " " | sed 's/"//g' | sed 's/,//g' | sed -e 's/\(.*\)/\L\1/' | xargs -n1 | tail -n 1)
echo "Selected app: $name"
app_name=$(echo $name | sed 's/ //g')
description="Titlebar color for $app_name"
new_color_scheme=~/.local/share/color-schemes/$app_name.colors

## Get color and convert hex (#RRGGBB) to dec (RR,GG,BB)
echo "$1"
if [ -z "$1" ]; then
    echo "Select color on the screen"
    color=$(grabc | awk '{print substr($0, 2)}')
    hexinput=`echo $color | tr '[:lower:]' '[:upper:]'`  # uppercase-ing
    a=`echo $hexinput | cut -c-2`
    b=`echo $hexinput | cut -c3-4`
    c=`echo $hexinput | cut -c5-6`
    r=`echo "ibase=16; $a" | bc`
    g=`echo "ibase=16; $b" | bc`
    b=`echo "ibase=16; $c" | bc`
    kde_color="$r,$g,$b"
else
    kde_color=$1
fi

echo "Selected color: $color ($kde_color)"

## Func for calculating floats
calc() {
    echo "$1" | bc -l | awk '{printf "%f", $0}'
}

## Check if selected color is more sutable with light colorscheme text
calc_color() {
    c=$(calc $1/255)
    l_comp=$(calc $c/12.92)
    if (( $(echo "$c > 0.03928" | bc) )); then
        l_comp=$(calc \($c+0.055\)^2.4)
    fi
    echo "$l_comp"
}

## Calculate contrast
calc_r=$(calc_color $r)
calc_g=$(calc_color $g)
calc_b=$(calc_color $b)
l=$(calc "$calc_r*0.2126 + $calc_g*0.7152 + $calc_b*0.0722")
contrast=$(calc 1.05/$l)

## If contrast is less than recommended text (4.5:1), then switch to light
if (( $(echo "$contrast < 4.5" | bc) )); then
    COLOR_SCHEME=$LIGHT_COLOR_SCHEME
else
    COLOR_SCHEME=$DARK_COLOR_SCHEME
fi

## Create a new colorscheme for the app
cp $COLOR_SCHEME $new_color_scheme
sed -i "s/BackgroundAlternate=.*/BackgroundAlternate=$kde_color/g" $new_color_scheme
sed -i "s/BackgroundNormal=.*/BackgroundNormal=$kde_color/g" $new_color_scheme
sed -i "/Name*/d" $new_color_scheme
echo "Name=$app_name" >> $new_color_scheme

KGROUPNUM=$(kreadconfig5 --file $KWINRULES --group "General" --key count)

## Check wether the rule already exists
for i in $(seq 1 $KGROUPNUM)
do
    description_value=$(kreadconfig5 --file ~/.config/kwinrulesrc --key Description --group $i)
    if [ "$description_value" = "$description" ]; then
        group=$i
        break
    fi   
done

## Func for writing config to a new group
wc() {
    kwriteconfig5 --file $KWINRULES --group "${group}" --key $1 "$2"
}

if [ -z ${group+x} ]; then
    group=$(($KGROUPNUM + 1))
    
    ## New rule
    wc Description "$description"
    wc decocolor "$app_name"
    wc decocolorrule 2
    wc wmclass "$name"
    wc wmclassmatch 1

    ## Increase config count number
    kwriteconfig5 --file $KWINRULES --group "General" --key count ${group}

    ## Apply changes
    qdbus org.kde.KWin /KWin reconfigure
else
    ## Apply a different colorscheme, so it forces a refresh on an existing rule
    wc decocolor "BreezeDark"
    qdbus org.kde.KWin /KWin reconfigure

    ## Wait some time, so the color-scheme properly applies
    sleep 1

    ## Apply modified custom color scheme
    wc decocolor "$app_name"
    qdbus org.kde.KWin /KWin reconfigure
fi

unset wc
unset calc
unset calc_color