#!/bin/bash

## Debugging
# set -x

## Editable variables
DARK_COLOR_SCHEME=/usr/share/color-schemes/BreezeDark.colors
LIGHT_COLOR_SCHEME=/usr/share/color-schemes/BreezeLight.colors
PREFIX="z_tkp_"

## Config file locations
KWINRULES=~/.config/kwinrulesrc
KCOLORSCHEMES=~/.local/share/color-schemes

## Make sure the folder for colorschemes exists
mkdir -p $KCOLORSCHEMES

echo "Click on app you want to configure"
##     ----- | Find app WM class         | get after '='   | remove "    | remove ,      | change to lowercase     | only last value
name=$(xprop | grep "WM_CLASS(STRING) =" | cut -f3- -d " " | sed 's/"//g' | sed 's/,//g' | sed -e 's/\(.*\)/\L\1/' | xargs -n1 | tail -n 1)
echo ""
echo "Selected app: $name"
app_name=$(echo $name | sed 's/ //g')
rule_name="$PREFIX$app_name"
new_color_scheme=$KCOLORSCHEMES/$PREFIX$app_name.colors

hex_2_dec() {
    echo $1 | tr '[:lower:]' '[:upper:]' | cut -c$2-$3 | xargs -I {} echo "ibase=16; {}" | bc
}

## Get color and convert hex (#RRGGBB) to dec (RR,GG,BB)
echo "$1"
if [ -z "$1" ]; then
    echo "Select color on the screen"
    color=$(kcolorchooser --print)
    r=`hex_2_dec ${color:1} 1 2`
    g=`hex_2_dec ${color:1} 3 4`
    b=`hex_2_dec ${color:1} 5 6`
    kde_color="$r,$g,$b"
else
    # Figure out which format was used
    color=$1
    if [[ $color =~ \#[a-fA-F0-9]{6}$ ]]; then
        # RGB
        r=`hex_2_dec ${color:1} 1 2`
        g=`hex_2_dec ${color:1} 3 4`
        b=`hex_2_dec ${color:1} 5 6`
        kde_color="$r,$g,$b"
    elif [[ $color =~ \#[a-fA-F0-9]{8}$ ]]; then
        # ARGB
        a=`hex_2_dec ${color:1} 1 2`
        r=`hex_2_dec ${color:1} 3 4`
        g=`hex_2_dec ${color:1} 5 6`
        b=`hex_2_dec ${color:1} 7 8`
        kde_color="$r,$g,$b,$a"
    elif [[ $color =~ \d{1,3}(?:,\d{1,3}){2,3}$ ]]; then
        # KDE format
        r=$(echo "$color" | cut -d ',' -f1)
        g=$(echo "$color" | cut -d ',' -f2)
        b=$(echo "$color" | cut -d ',' -f3)
        kde_color=$1
    else
        echo "Specified color format not supported!"
        exit 1
    fi
fi

echo "Selected color: $color ($kde_color)"

## Func for calculating floats
calc() {
    echo "$1" | bc -l | awk '{printf "%f", $0}'
}

## Check if selected color is more sutable with light colorscheme text
calc_color() {
    c=$(calc $1/255)
    l_comp=$(calc $c/12.92)
    if (( $(echo "$c > 0.03928" | bc) )); then
        l_comp=$(calc e\(l\($c+0.055\)*2.4\))
    fi
    echo "$l_comp"
}

## Calculate contrast
calc_r=$(calc_color $r)
calc_g=$(calc_color $g)
calc_b=$(calc_color $b)
l=$(calc "$calc_r*0.2126 + $calc_g*0.7152 + $calc_b*0.0722 + 0.05")
contrast=$(calc 1.05/$l)

## If contrast is less than recommended text (4.5:1), then switch to light
if (( $(echo "$contrast < 4.5" | bc) )); then
    COLOR_SCHEME=$LIGHT_COLOR_SCHEME
else
    COLOR_SCHEME=$DARK_COLOR_SCHEME
fi

## Create a new colorscheme for the app
cp $COLOR_SCHEME $new_color_scheme
sed -i "s/BackgroundAlternate=.*/BackgroundAlternate=$kde_color/g" $new_color_scheme
sed -i "s/BackgroundNormal=.*/BackgroundNormal=$kde_color/g" $new_color_scheme
sed -i "/Name*/d" $new_color_scheme
echo "Name=$app_name" >> $new_color_scheme

KGROUPNUM=$(kreadconfig5 --file $KWINRULES --group "General" --key count)

## Check wether the rule already exists
for i in $(seq 1 $KGROUPNUM)
do
    rule_name_value=$(kreadconfig5 --file $KWINRULES --key Description --group $i)
    if [ "$rule_name_value" = "$rule_name" ]; then
        group=$i
        break
    fi   
done

## Func for writing config to a new group
wc() {
    kwriteconfig5 --file $KWINRULES --group "${group}" --key $1 "$2"
}

if [ -z ${group+x} ]; then
    group=$(($KGROUPNUM + 1))
    
    ## New rule
    wc Description "$rule_name"
    wc decocolor "$rule_name"
    wc decocolorrule 2
    wc wmclass "$name"
    wc wmclassmatch 1

    ## Increase config count number
    kwriteconfig5 --file $KWINRULES --group "General" --key count ${group}

    ## Apply changes
    qdbus org.kde.KWin /KWin reconfigure
else
    ## Apply a different colorscheme, so it forces a refresh on an existing rule
    wc decocolor "BreezeDark"
    qdbus org.kde.KWin /KWin reconfigure

    ## Wait some time, so the color-scheme properly applies
    sleep 1

    ## Apply modified custom color scheme
    wc decocolor "$rule_name"
    qdbus org.kde.KWin /KWin reconfigure
fi

unset wc
unset calc
unset calc_color
unset hex_2_dec
